name: amass
version: '3.1.5'
summary: In-depth Attack Surface Mapping and Asset Discovery
description: The OWASP Amass Project has developed a tool to help information security professionals perform network mapping of attack surfaces and perform external asset discovery using open source information gathering and active reconnaissance techniques.
icon: images/snapcraft_icon.png
grade: stable
confinement: strict


apps:
  amass:
    command: bin/amass
    plugs: [home, network, removable-media, personal-files]


plugs:
  dot-amass:
    interface: personal-files
    write:
    - $HOME/.amass
    - $HOME/.config/amass


parts:
  go:
    source-tag: go1.13

  amass:
    after: [go]
    source: https://github.com/OWASP/Amass
    source-type: git
    plugin: go
    go-importpath: github.com/OWASP/Amass
    override-build: |
      echo "\nStarting override-build for amass part:"
      export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
      cd $GOPATH/src/github.com/OWASP/Amass
      go install ./...
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      mv $GOPATH/bin/amass $SNAPCRAFT_PART_INSTALL/bin/amass
      strip --remove-section=.comment --remove-section=.note $SNAPCRAFT_PART_INSTALL/bin/amass
