# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  test:
    docker:
      - image: circleci/golang:1.14

    environment:
      GO111MODULE: "on"
      TEST_RESULTS: /tmp/test_results

    working_directory: /go/src/github.com/OWASP/Amass

    steps:
      - checkout
      - run:
          name: "Amass Unit Tests and Coverage Reports"
          environment:
            GO111MODULE: "on"
          command: |
            cd /go/src/github.com/OWASP/Amass
            go get -u github.com/OWASP/Amass/v3/...
            go test -race -coverprofile=$TEST_RESULTS/coverage.txt -covermode=atomic ./...

workflows:
  version: 2.1
  main:
    jobs:
      - test
#      - binaries:
#          requires:
#            - test
#          filters:
#            branches:
#              only: master
